create_clock -period 10.000 -name clk_100 -waveform {0.000 5.000} [get_ports Clk]

set_property PACKAGE_PIN N15 [get_ports Clk]
set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property PACKAGE_PIN T13 [get_ports {gpio_usb_int_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_usb_int_tri_i[0]}]
set_property PACKAGE_PIN V13 [get_ports gpio_usb_rst_tri_o]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_usb_rst_tri_o]
set_property PACKAGE_PIN J2 [get_ports Reset]
set_property IOSTANDARD LVCMOS33 [get_ports Reset]
set_property PACKAGE_PIN U12 [get_ports usb_spi_miso]
set_property PACKAGE_PIN V15 [get_ports usb_spi_mosi]
set_property PACKAGE_PIN V14 [get_ports usb_spi_sclk]
set_property PACKAGE_PIN T12 [get_ports usb_spi_ss]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_ss]
set_property PACKAGE_PIN B16 [get_ports uart_rtl_0_rxd]
set_property PACKAGE_PIN A16 [get_ports uart_rtl_0_txd]
set_property IOSTANDARD LVCMOS18 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN G1 [get_ports {SW_lfo[0]}]
set_property PACKAGE_PIN F2 [get_ports {SW_lfo[1]}]
set_property PACKAGE_PIN F1 [get_ports {SW_osc[1]}]
set_property PACKAGE_PIN E2 [get_ports {SW_osc[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_lfo[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_lfo[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_osc[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_osc[0]}]
set_property PACKAGE_PIN B13 [get_ports audio_outL]
set_property PACKAGE_PIN B14 [get_ports audio_outR]
set_property IOSTANDARD LVCMOS18 [get_ports audio_outL]
set_property IOSTANDARD LVCMOS18 [get_ports audio_outR]
set_property DRIVE 4 [get_ports audio_outR]
set_property DRIVE 4 [get_ports audio_outL]



set_property IOSTANDARD LVCMOS33 [get_ports but_filt_sel_dn]
set_property IOSTANDARD LVCMOS33 [get_ports but_filt_sel_up]
set_property IOSTANDARD LVCMOS33 [get_ports SW_filt_bp]
set_property SLEW SLOW [get_ports audio_outL]
set_property SLEW SLOW [get_ports audio_outR]
set_property PACKAGE_PIN E1 [get_ports SW_filt_bp]
set_property PACKAGE_PIN G2 [get_ports but_filt_sel_dn]
set_property PACKAGE_PIN J1 [get_ports but_filt_sel_up]


create_generated_clock -name km/kdb_filt_dn/db_clk_reg_n_0 -source [get_ports Clk] -divide_by 250000 [get_pins km/kdb_filt_dn/db_clk_reg/Q]
create_generated_clock -name km/kdb_filt_up/db_clk -source [get_ports Clk] -divide_by 250000 [get_pins km/kdb_filt_up/db_clk_reg/Q]
