create_clock -period 10.000 -name clk_100 -waveform {0.000 5.000} [get_ports Clk]




set_property PACKAGE_PIN B14 [get_ports audio_outR]
set_property PACKAGE_PIN B13 [get_ports audio_outL]
set_property PACKAGE_PIN N15 [get_ports Clk]
set_property PACKAGE_PIN J2 [get_ports Reset]
set_property PACKAGE_PIN J1 [get_ports Trig]
set_property PACKAGE_PIN G1 [get_ports {SW[0]}]
set_property PACKAGE_PIN F2 [get_ports {SW[1]}]
set_property PACKAGE_PIN F1 [get_ports {SW[2]}]
set_property PACKAGE_PIN E2 [get_ports {SW[3]}]
set_property PACKAGE_PIN E1 [get_ports {SW[4]}]
set_property PACKAGE_PIN D2 [get_ports {SW[5]}]
set_property PACKAGE_PIN D1 [get_ports {SW[6]}]
set_property PACKAGE_PIN C2 [get_ports {SW[7]}]
set_property PACKAGE_PIN B2 [get_ports {SW[8]}]
set_property PACKAGE_PIN A4 [get_ports {SW[9]}]
set_property PACKAGE_PIN A5 [get_ports {SW[10]}]
set_property PACKAGE_PIN A6 [get_ports {SW[11]}]
set_property PACKAGE_PIN C7 [get_ports {SW[12]}]
set_property PACKAGE_PIN A7 [get_ports {SW[13]}]
set_property PACKAGE_PIN B7 [get_ports {SW[14]}]
set_property PACKAGE_PIN A8 [get_ports {SW[15]}]
set_property PACKAGE_PIN C13 [get_ports {test_audio[0]}]
set_property PACKAGE_PIN C14 [get_ports {test_audio[1]}]
set_property PACKAGE_PIN D14 [get_ports {test_audio[2]}]
set_property PACKAGE_PIN D15 [get_ports {test_audio[3]}]
set_property PACKAGE_PIN D16 [get_ports {test_audio[4]}]
set_property PACKAGE_PIN F18 [get_ports {test_audio[5]}]
set_property PACKAGE_PIN E17 [get_ports {test_audio[6]}]
set_property PACKAGE_PIN D17 [get_ports {test_audio[7]}]
set_property PACKAGE_PIN C17 [get_ports {test_audio[8]}]
set_property PACKAGE_PIN B18 [get_ports {test_audio[9]}]
set_property PACKAGE_PIN A17 [get_ports {test_audio[10]}]
set_property PACKAGE_PIN B17 [get_ports {test_audio[11]}]
set_property PACKAGE_PIN C18 [get_ports {test_audio[12]}]
set_property PACKAGE_PIN D18 [get_ports {test_audio[13]}]
set_property PACKAGE_PIN E18 [get_ports {test_audio[14]}]
set_property PACKAGE_PIN G17 [get_ports {test_audio[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test_audio[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test_audio[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test_audio[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test_audio[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test_audio[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test_audio[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test_audio[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test_audio[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test_audio[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test_audio[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test_audio[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test_audio[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test_audio[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test_audio[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test_audio[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test_audio[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports Trig]
set_property IOSTANDARD LVCMOS18 [get_ports audio_outL]
set_property IOSTANDARD LVCMOS18 [get_ports audio_outR]
set_property IOSTANDARD LVCMOS18 [get_ports Clk]
set_property IOSTANDARD LVCMOS18 [get_ports Reset]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW[0]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list Clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {test_audio_OBUF[0]} {test_audio_OBUF[1]} {test_audio_OBUF[2]} {test_audio_OBUF[3]} {test_audio_OBUF[4]} {test_audio_OBUF[5]} {test_audio_OBUF[6]} {test_audio_OBUF[7]} {test_audio_OBUF[8]} {test_audio_OBUF[9]} {test_audio_OBUF[10]} {test_audio_OBUF[11]} {test_audio_OBUF[12]} {test_audio_OBUF[13]} {test_audio_OBUF[14]} {test_audio_OBUF[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list Reset_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list audio_outR_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list Trig_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list p_0_in]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets Clk_IBUF_BUFG]
