create_clock -period 10.000 -name clk_100 -waveform {0.000 5.000} [get_ports Clk]

set_property PACKAGE_PIN N15 [get_ports Clk]
set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property PACKAGE_PIN T13 [get_ports {gpio_usb_int_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_usb_int_tri_i[0]}]
set_property PACKAGE_PIN V13 [get_ports gpio_usb_rst_tri_o]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_usb_rst_tri_o]
set_property PACKAGE_PIN J2 [get_ports Reset]
set_property IOSTANDARD LVCMOS33 [get_ports Reset]
set_property PACKAGE_PIN U12 [get_ports usb_spi_miso]
set_property PACKAGE_PIN V15 [get_ports usb_spi_mosi]
set_property PACKAGE_PIN V14 [get_ports usb_spi_sclk]
set_property PACKAGE_PIN T12 [get_ports usb_spi_ss]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports usb_spi_ss]
set_property PACKAGE_PIN B16 [get_ports uart_rtl_0_rxd]
set_property PACKAGE_PIN A16 [get_ports uart_rtl_0_txd]
set_property IOSTANDARD LVCMOS18 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN G1 [get_ports {SW_lfo[0]}]
set_property PACKAGE_PIN F2 [get_ports {SW_lfo[1]}]
set_property PACKAGE_PIN F1 [get_ports {SW_osc[1]}]
set_property PACKAGE_PIN E2 [get_ports {SW_osc[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_lfo[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_lfo[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_osc[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_osc[0]}]
set_property PACKAGE_PIN B13 [get_ports audio_outL]
set_property PACKAGE_PIN B14 [get_ports audio_outR]
set_property IOSTANDARD LVCMOS18 [get_ports audio_outL]
set_property IOSTANDARD LVCMOS18 [get_ports audio_outR]
set_property DRIVE 8 [get_ports audio_outR]
set_property DRIVE 8 [get_ports audio_outL]



set_property IOSTANDARD LVCMOS33 [get_ports but_filt_sel_dn]
set_property IOSTANDARD LVCMOS33 [get_ports but_filt_sel_up]
set_property IOSTANDARD LVCMOS33 [get_ports SW_filt_bp]
set_property SLEW SLOW [get_ports audio_outL]
set_property SLEW SLOW [get_ports audio_outR]
set_property PACKAGE_PIN E1 [get_ports SW_filt_bp]
set_property PACKAGE_PIN G2 [get_ports but_filt_sel_dn]
set_property PACKAGE_PIN J1 [get_ports but_filt_sel_up]



create_generated_clock -name lfo/lfo_441_clk/aclk -source [get_ports Clk] -divide_by 2268 [get_pins lfo/lfo_441_clk/clock_out_reg/Q]

create_generated_clock -name oscillator/osc_441_clk/aclk -source [get_ports Clk] -divide_by 2268 [get_pins oscillator/osc_441_clk/clock_out_reg/Q]




set_property PACKAGE_PIN B3 [get_ports {hex_grid[3]}]
set_property PACKAGE_PIN C3 [get_ports {hex_grid[2]}]
set_property PACKAGE_PIN H6 [get_ports {hex_grid[1]}]
set_property PACKAGE_PIN G6 [get_ports {hex_grid[0]}]
set_property PACKAGE_PIN E6 [get_ports {hex_seg[0]}]
set_property PACKAGE_PIN B4 [get_ports {hex_seg[1]}]
set_property PACKAGE_PIN D5 [get_ports {hex_seg[2]}]
set_property PACKAGE_PIN C5 [get_ports {hex_seg[3]}]
set_property PACKAGE_PIN D7 [get_ports {hex_seg[4]}]
set_property PACKAGE_PIN D6 [get_ports {hex_seg[5]}]
set_property PACKAGE_PIN C4 [get_ports {hex_seg[6]}]
set_property PACKAGE_PIN B5 [get_ports {hex_seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {SW_lfo_scale[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_lfo_scale[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_lfo_scale[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_lfo_scale[0]}]
set_property PACKAGE_PIN A8 [get_ports {SW_lfo_scale[3]}]
set_property PACKAGE_PIN B7 [get_ports {SW_lfo_scale[2]}]
set_property PACKAGE_PIN A7 [get_ports {SW_lfo_scale[1]}]
set_property PACKAGE_PIN C7 [get_ports {SW_lfo_scale[0]}]

set_property DRIVE 4 [get_ports audio_outLtest]
set_property PACKAGE_PIN L18 [get_ports audio_outLtest]
set_property PACKAGE_PIN L17 [get_ports audio_outRtest]
set_property DRIVE 4 [get_ports audio_outRtest]
set_property IOSTANDARD LVCMOS33 [get_ports audio_outRtest]
set_property IOSTANDARD LVCMOS33 [get_ports audio_outLtest]

#create_generated_clock -name lfo/lfo_441_clk/clock_out_reg_0 -source [get_pins lfo/lfo_5meg/inst/mmcm_adv_inst/CLKOUT0] -divide_by 113 [get_pins lfo/lfo_441_clk/clock_out_reg/Q]
#create_generated_clock -name oscillator/osc_441_clk/clock_out_reg_0 -source [get_pins oscillator/osc_5meg/inst/mmcm_adv_inst/CLKOUT0] -divide_by 113 [get_pins oscillator/osc_441_clk/clock_out_reg/Q]


set_property PACKAGE_PIN A6 [get_ports SW_pwm_scaler]
set_property IOSTANDARD LVCMOS33 [get_ports SW_pwm_scaler]

create_generated_clock -name am_adsr_441/clk_441 -source [get_ports Clk] -divide_by 2268 [get_pins am_adsr_441/clock_out_reg/Q]

set_property PACKAGE_PIN D1 [get_ports SW_AM_bypass]
set_property IOSTANDARD LVCMOS33 [get_ports SW_AM_bypass]
set_property PACKAGE_PIN C2 [get_ports {SW_sel_adsr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_sel_adsr[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_sel_adsr[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_sel_adsr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_sel_adsr[0]}]
set_property PACKAGE_PIN B2 [get_ports {SW_sel_adsr[1]}]
set_property PACKAGE_PIN A4 [get_ports {SW_sel_adsr[2]}]
set_property PACKAGE_PIN A5 [get_ports {SW_sel_adsr[3]}]
set_property PACKAGE_PIN H2 [get_ports but_inc_adsr]
set_property IOSTANDARD LVCMOS33 [get_ports but_inc_adsr]
set_property PACKAGE_PIN E4 [get_ports {hex_grid_adsr[0]}]
set_property PACKAGE_PIN E3 [get_ports {hex_grid_adsr[1]}]
set_property PACKAGE_PIN F5 [get_ports {hex_grid_adsr[2]}]
set_property PACKAGE_PIN H5 [get_ports {hex_grid_adsr[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_adsr[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_adsr[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_adsr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_adsr[0]}]
set_property PACKAGE_PIN F3 [get_ports {hex_seg_adsr[0]}]
set_property PACKAGE_PIN G5 [get_ports {hex_seg_adsr[1]}]
set_property PACKAGE_PIN J3 [get_ports {hex_seg_adsr[2]}]
set_property PACKAGE_PIN H4 [get_ports {hex_seg_adsr[3]}]
set_property PACKAGE_PIN F4 [get_ports {hex_seg_adsr[4]}]
set_property PACKAGE_PIN H3 [get_ports {hex_seg_adsr[5]}]
set_property PACKAGE_PIN E5 [get_ports {hex_seg_adsr[6]}]
set_property PACKAGE_PIN J4 [get_ports {hex_seg_adsr[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_adsr[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_adsr[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_adsr[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_adsr[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_adsr[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_adsr[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_adsr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_adsr[0]}]
